name: GunForSurvival
main: ommadawn46.gunForSurvival.GunForSurvival
version: 0.0.1

commands:
   gfs:
      description: Give a GFS Item to Player
      usage: /gfs <player> <itemName>
      permission: GunForSurvival.gts
      permission-message: You don't have <permission>
   gfslist:
      description: Show the GFS Items List
      usage: /gfslist
      permission: GunForSurvival.gts
      permission-message: You don't have <permission>